using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PollWebServiceTest_BARTScheduleForStation
{
    class BARTScheduleForStation
    {
    }

    // generated by jsonutils.com
    public class Xmlinfo
    {
        public string version { get; set; }
        public string encoding { get; set; }
    }

    public class Uri
    {
        public string cdatasection { get; set; }
    }

    public class Item
    {
        public string line { get; set; }
        public string trainHeadStation { get; set; }
        public string origTime { get; set; }
        public string bikeflag { get; set; }
        public string load { get; set; }
    }

    public class Station
    {
        public string name { get; set; }
        public string abbr { get; set; }
        public IList<Item> item { get; set; }
    }

    public class Root
    {
        public Uri uri { get; set; }
        public string date { get; set; }
        public Station station { get; set; }
        public string message { get; set; }
    }

    public class BART_StationSchedule
    {
        public Xmlinfo xmlinfo { get; set; }
        public Root root { get; set; }
    }
    // end generated by jsonutils.com
}
